export const archis = [
  'Sourizoto le Collant (Souris Grise)',
  'Mosketère le Dévoué (Moskito)',
  'Arakule la Revancharde (Arakne)',
  'Boudalf le Blanc (Boufton Blanc)',
  'Boulgouvril le Lointain (Boufton Noir)',
  'Tofumanchou l\'Empereur (Tofu Maléfique)',
  'Arachitik la Souffreteuse (Arakne Malade)',
  'Pioustone le Problème (Piou Bleu)',
  'Pioulbrineur le Mercenaire (Piou Jaune)',
  'Pioulette la Coquine (Piou Rouge)',
  'Pioukas la Plante (Piou Vert)',
  'Pioussokrim le Délétère (Piou Violet)',
  'Craraboss le Féérique (Crabe)',
  'Larvonika l\'Instrument (Larve Bleue)',
  'Pioufe la Maquillée (Piou Rose)',
  'Tofuldebeu l\'Explosif (Tofu)',
  'Tofurapin le Pétri (Tofu Malade)',
  'Chamchie le Difficile (Champ Champ)',
  'Pissdane l\'Insipide (Pissenlit Diabolique)',
  'Araknay la Galopante (Arakne Agressive)',
  'Bandapar l\'exclu (Bandit Manchot)',
  'Roz la Magicienne (Rose Démoniaque)',
  'Gelanal le Huileux (Gelée Bleue)',
  'Kwoanneur le Frimeur (Kwoan)',
  'Larchimaide la poussée (Larve Verte)',
  'Boufdégou le Refoulant (Bouftou)',
  'Kolforthe l\'Indécollable (Kolérat)',
  'Geloliaine l\'Aérien (Gelée Menthe)',
  'Larvastrès le Subjectif (Larve Orange)',
  'Serpistol l\'Illustre (Serpentin)',
  'Tiwa\'Missou le Gateux (Black Tiwabbit)',
  'Boudur le Raide (Boulanger sombre)',
  'Tiwalpé le Dévêtu (Tiwabbit)',
  'Tiowflan le Lâche (Tiwabbit Kiaffin)',
  'Tour le Vice (Tournesol Sauvage)',
  'Bandson le Tonitruant (Bandit du Clan des Roublards)',
  'Gobstinais le Têtu (Gobet)',
  'Nodkoku le Trahi (Nodkoko)',
  'Tikosto le Mousse (Tikoko)',
  'Trukul le Lent (Trukikol)',
  'Sangria le Fruité (Sanglier)',
  'Champayr le Disjoncté (Champa Vert)',
  'Étoilette la Bouchée (Étoile de la Mer d\'Asse)',
  'Vampunor le Glacial (Vampire)',
  'Bilvoezé le Bonimenteur (Biblop Coco)',
  'Bi le Partageur (Biblop Griotte)',
  'Bitsou le Quêteur (Biblop Indigo)',
  'Bitsou le Rieur (Biblop Reinette)',
  'Chevaustine le Reconstruit (Gob-Trotteur)',
  'Milipussien le Géant (Milirat Strubien)',
  'Boostif l\'Affamé (Boo)',
  'Preskapwal le Tendancieux (Prespic)',
  'Chonstip la Passagère (Cochon de Lait)',
  'Torthur la Lutte (Tortue Jaune)',
  'Wabbitud le Constant (Wabbit)',
  'Porfavor le Quémandeur (Berger Porkass)',
  'Robiolego l\'Assemblé (Robionicle)',
  'Bouflet le Puéril (Chef de Guerre Bouftou)',
  'Cromikay le Néophyte (Croc Gland)',
  'Tortenssia la Fleurie (Tortue Bleue)',
  'Bambouské le Camouflé (Bambouto)',
  'Corpat le Vampire (Corbac)',
  'Pichduite le Totem (Pichon Blanc)',
  'Pichdourse le Puissant (Pichon Bleu)',
  'Pichtoire l\'Erudit (Pichon Orange)',
  'Pichakoté le Dégoûtant (Pichon Vert)',
  'Tortorak le Cornu (Tortue Rouge)',
  'Maître Amboat le Moqueur (Maître Vampire)',
  'Robocoop l\'Échangé (Robot Fléau)',
  'Fourapin le Chaud (Fourbasse)',
  'Milipatte la Griffe (Milimulou)',
  'Minoscour le Sauveur (Minoskito)',
  'Neufedur le Flottant (Noeul)',
  'Tortilleur le Coulé (Tortue Verte)',
  'Bworkmage le Respectueux (Bwork Mage)',
  'Wagnagnah le Sanglant (Black Wabbit)',
  'Crognan le Barbare (Crowneille)',
  'Rostensyl la Cuisinière (Rose Obscure)',
  'Minsinistre l\'Elu (Mineur Sombre)',
  'Barchwork le Multicolore (Bwork Archer)',
  'Champayt l\'Odorant (Champa Bleu)',
  'Chamflay le Ballonné (Champa Marron)',
  'Chamdblé le Cultivé (Champa Rouge)',
  'Craquetuss le Piquant (Craqueboule)',
  'Mandalo l\'Aqueuse (Mandrine)',
  'Mallopiée l\'Épineuse (Malle Outillée)',
  'Garsim le Mort (Gargrouille)',
  'Draglida la Disparue (Dragodinde Amande Sauvage)',
  'Gelaviv le Glaçon (Gelée Rouge)',
  'Watdogue le Bien Nommé (Wabbit Squelette)',
  'Chafalfer l\'Optimiste (Chafer Invisible)',
  'Crakmitaine le Faucheur (Craqueleur)',
  'Bworkasse le Dégoûtant (Bwork)',
  'Abrakroc l\'Edenté (Abraknyde)',
  'Krapahut le Randonneur (Kraméléhon)',
  'Scapé l\'Epée (Scarafeuille Blanc)',
  'Scarfaysse le Balafré (Scarafeuille Bleu)',
  'Scarouarze l\'Epopsée (Scarafeuille Rouge)',
  'Scaramel le Fondant (Scarafeuille Vert)',
  'Ribibi le Cher (Rib)',
  'Blorie l\'Assourdissante (Blop Coco)',
  'Blordur l\'Infect (Blop Griotte)',
  'Bloporte le Veule (Blop Indigo)',
  'Blof l\'Apathique (Blop Reinette)',
  'Boombata le Garde (Boomba)',
  'Farlon l\'Enfant (Cochon de farle)',
  'Scaratyne l\'Huître (Scaratos)',
  'Chaffoin le Sournois (Chafer Fantassin)',
  'Picht le Brioché (Pichon Kloune)',
  'Tronkoneuze la Tranchante (Tronknyde)',
  'Abrakadnuzar (Abrakne)',
  'Chafemal le Bagarreur (Chafer)',
  'Crolnareff l\'Exilé (Crocodaille)',
  'Radoutable le Craint (Scélérat Strubien)',
  'Scorpitène l\'Enflammé (Scorbute)',
  'Dragnoute l\'Irascible (Dragodinde Rousse Sauvage)',
  'Bulsavon le Gonflé (Bulbuisson)',
  'Crustterus l\'Organique (Crustorail Kouraçao)',
  'Crustensyl le Pragmatique (Crustorail Malibout)',
  'Cruskof le Rustre (Crustorail Morito)',
  'Crusmeyer le Pervers (Crustorail Passaoh)',
  'Forboyar l\'Enigmatique (Forgeron Sombre)',
  'Floriste la Cannibale (Floristile)',
  'Arabord la Cruche (Arakne Majeure)',
  'Grandilok le Clameur (Grand Pa Wabbit)',
  'Wokenrol le Danseur (Wo Wabbit)',
  'Cavordemal le Sorcier (Cavalier Porkass)',
  'Aboudbra le Porteur (Aboub)',
  'Ameur la Laide (Amlub)',
  'Codenlgaz le Problème (Codem)',
  'Ginsenk le Stimulant (Gink)',
  'Kiroyal le Sirupeux (Kirevam)',
  'Let le Rond (Let Emoliug)',
  'Nelvin le Boulet (Negbib)',
  'Nipulnislip l\'Exibitionniste (Nipul)',
  'Osuxion le Vampirique (Osurc)',
  'Susbewl l\'Hypocrite (Susej)',
  'Koktèle le Secoué (Kokoko)',
  'Chafmarcel le Fêtard (Chafer Archer)',
  'Chalan le Commerçant (Chafer Lancier)',
  'Ramitant le Dillettante (Ramane d\'Égoutant)',
  'Doktopuss le Maléfique (Dok Alako)',
  'Germinol l\'Indigent (Gamino)',
  'Koalastrof la Naturelle (Koalak Immature)',
  'Ouature la Mobile (La Ouassingue)',
  'Ouassébo l\'Esthète (Le Ouassingue)',
  'Ouashouah l\'Exubérant (Le Ouassingue Entourbé)',
  'Palmito le Menteur (Palmifleur Malibout)',
  'Palmiche le Serein (Palmifleur Morito)',
  'Palmiflette le Convivial (Palmifleur Passaoh)',
  'Sampi l\'Eternel (Sanglier des Plaines)',
  'Abrakildas le Vénérable (Abraknyde Vénérable)',
  'Cramikaz le Suicidaire (Craqueleur des Plaines)',
  'Koko la Violente (Kokom)',
  'Chafrit le Barbare (Chafer d\'Élite)',
  'Craquetou le Fissuré (Craqueboule Poli)',
  'Maître Onom le Régulier (Maître Bolet)',
  'Grenuche la Gentille (Grenufar)',
  'Kannibal le Lecteur (Kanniboul Archer)',
  'Kapota la Fraise (Kanniboul Jav)',
  'Kannémik le Maigre (Kanniboul Sarbak)',
  'Kannisterik le Forcené (Kanniboul Thierry)',
  'Sarkastik l\'Incompris (Sarkapwane)',
  'Palmbytch la Bronzée (Palmifleur Kouraçao)',
  'Ratlbol l\'Aigri (Rat d\'Égoutant)',
  'Ougaould le Parasite (Chafer Draugr)',
  'Corboyard l\'Enigmatique (Corailleur)',
  'Kwaké le Piraté (Kwak de Vent)',
  'Kwakwatique le Trempé (Kwak de Glace)',
  'Kwakamole l\'Apétissant (Kwak de Terre)',
  'Kwakolak le Chocolaté (Kwak de Flamme)',
  'Porsalé le Rieur (Porsalu)',
  'Dragioli le Succulent (Dragacé)',
  'Vetaurine l\'Énergisé (Vétauran)',
  'Moumoute la Douce (Moumoule)',
  'Parapadkouï l\'Émasculé (Parashukouï)',
  'Serpistule le Purulent (Serpiplume)',
  'Bebetto l\'Intellectuel (Betto)',
  'Akaka le Souillé (Akakwa)',
  'Rauligo le Sale (Raul Mops)',
  'Caboume l\'Artilleur (Canondorf)',
  'Tilolo la Bien Moulée (Lolojiki)',
  'Nakuneye le Borgne (Nakunbra)',
  'Chiendanslémain l\'Illusionniste (Chiendent)',
  'Dragstayr le Fonceur (Dragoeuf Calcaire)',
  'Dragmoclaiss le Fataliste (Dragoeuf Ardoise)',
  'Dragkouine la Déguisée (Dragoeuf Argile)',
  'Dragnostik le Sceptique (Dragoeuf Charbon)',
  'Koamaembair le Coulant (Koalak Coco)',
  'Koakofrui le Confit (Koalak Griotte)',
  'Koaskette la Chapelière (Koalak Indigo)',
  'Koarmit la Batracienne (Koalak Reinette)',
  'Ratéhaifaim le Professeur (Rat d\'Hyoactif)',
  'Sparoket le Lanceur (Sparo)',
  'Fanlabiz le Véloce (Fantôme Apero)',
  'Fandanleuil le Précis (Fantôme aux Plates)',
  'Fantoch le Pantin (Fantôme Hicide)',
  'Fantrask le Rêveur (Fantôme Égérie)',
  'Barebourd le Comte (Barbroussa)',
  'Nerdeubeu le Flagellant (Nerbe)',
  'Crok le Beau (Chef Crocodaille)',
  'Toufou le Benêt (Bitouf des Plaines)',
  'Crathdogue le Cruel (Craqueleur Poli)',
  'Alhoui le Répondeur (Alhyène)',
  'Pantacour le Long (Panthégros)',
  'Orfélyre le Charmeur (Orfélin)',
  'Félyssion la Gourmande (Félygiène)',
  'Kanibière l\'Encordée (Kaniblou)',
  'Kanasukr le Mielleux (Kanigrou)',
  'Mufguedin le Suprême (Mufafah)',
  'Muloufok l\'Hilarant (Mulou)',
  'Bonpake le Chavireur (Ishigro Pake)',
  'Kido l\'Âtre (Kido)',
  'Kilimanj\'haro le Grimpeur (Kilibriss)',
  'Larvaloeil l\'Émue (Larve Champêtre)',
  'Souristiti l\'Immortalisée (Souris Verte)',
  'Bourde le Maladroit (Bourdard)',
  'Fouflay le Retombé (Foufayteur)',
  'Dragonienne l\'Econome (Dragueuse)',
  'Guerrite le Veilleur (Guerrier Koalak)',
  'Lichangora l\'Immaculée (Lichangoro)',
  'Craquecrac l\'Endurant (Craquelourd)',
  'Warkolad l\'Etreinte (Warko Marron)',
  'Inopenope le Négatif (Ino-Naru)',
  'Abrakanette l\'Encapsulé (Abraknyde Sombre)',
  'Tétonée la Plantureuse (Tétonuki)',
  'Fossamoel le Juteux (Fossoyeur Koalak)',
  'Gloubibou le Gars (Gloutovore)',
  'Koasossyal le Psychopathe (Koalak Forestier)',
  'Pékeutar le Tireur (Pékeualak)',
  'Piradain le Pingre (Piralak)',
  'Abraklette le Fondant (Abrakne Sombre)',
  'Koamag\'oel le Défiguré (Chevaucheur Koalak)',
  'Meuroup le Prêtre (Meupette)',
  'Rooroku l\'Imposant (Kurookin)',
  'Dragdikal le Décisif (Dragnarok)',
  'Dragobert le Monarque (Draguaindrop)',
  'Diskord le Belliqueux (Disciple Zoth)',
  'Brouste l\'Humiliant (Brouture)',
  'Bitoven le Musicien (Bitouf Sombre)',
  'Ecorfé la Vive (Fécorce)',
  'Floanna la Blonde (Floribonde)',
  'Koalvissie le Chauve (Koalak Sanguin)',
  'Koalabois le Calorifère (Koalak Farouche)',
  'Mamakomou l\'Âge (Mama Koalak)',
  'Momikonos la Bandelette (Momie Koalak)',
  'Boulivert le Géant (Bourbassingue)',
  'Wara l\'Amer (Warko Violet)',
  'Gastroth la Contagieuse (Gamine Zoth)',
  'Guerumoth le Collant (Guerrier Zoth)',
  'Tourbiket le Virevoletant (Tourbassingue)',
  'Abrakine le Sombre (Abrakleur Sombre)',
  'Dragminster le Magicien (Dragoss Calcaire)',
  'Drageaufol la Joyeuse (Dragoss Ardoise)',
  'Dragtarus le Bellâtre (Dragoss Argile)',
  'Draquetteur le Voleur (Dragoss Charbon)',
  'Fangshui la Dysorthographiée (Fangshu)',
  'Pétarfoutu le Mouillé (Pétartifoux)',
  'Drakolage le Tentateur (Drakoalak)',
  'Faufoll la Joyeuse (Fauchalak)',
  'Bigbadaboum l\'Élémentaire (Boumbardier)',
  'Maître Koantik le Théoricien (Maître Koalak)',
  'Poolopo la Traditionnelle (Poolay)',
  'Trooyé l\'Oxydé (Trollaraj)',
  'Seripoth l\'Ennemi (Sergent Zoth)',
  'Kaskapointhe la Couverte (Kaskargo)',
  'Toutouf le Velu (Bitouf Aérien)',
  'Abrinos le Clair (Abrakleur Clair)',
  'Don Kizoth l\'Obstiné (Maître Zoth)',
  'Chamiléro le Malchanceux (Champaknyde)',
  'Crachefouxtre le Surpris (Crachefoux)',
  'Tromplamor le Survivant (Tromperelle)',
  'Chamoute le Duveteux (Champodonte)',
  'Tsucékoi la Colporteuse (Tsukinochi)',
  'Tambouille le Gastronome (Tambouraï)',
  'Champoul l\'Illuminé (Champbis)',
  'Champolyon le Polyglotte (Champ À Gnons)',
  'Champmé le Méchant (Champmane)',
  'Onabuémangé la Rassasiée (Onabu-Geisha)',
  'Jiankor le Radoteur (Jiangshi-Nobi)',
  'Tronquette la Réduite (Rouquette)',
  'Roy le Merlin (Roissingue)',
  'Madgang le Docteur (Madura)',
  'Bakaglace le Congelé (Bakazako)',
  'Kaonucléair l\'Instable (Kaonashi)',
  'Tsumani l\'Inondeur (Tsume-Bozu)',
]
