export const bosses = [
  'Mob l\'Éponge',
  'Bouftou Royal',
  'Tournesol Affamé',
  'Gelée Royale Bleue',
  'Gelée Royale Menthe',
  'Shin Larve',
  'Wabbit GM',
  'Scarabosse Doré',
  'Bworkette',
  'Dragon Cochon',
  'Mominotor',
  'Déminoboule',
  'Tofu Royal',
  'Blop Coco Royal',
  'Blop Griotte Royal',
  'Blop Indigo Royal',
  'Blop Reinette Royal',
  'Rat Noir',
  'Rat Blanc',
  'Minotoror',
  'Hell Mina',
  'Tanukouï San',
  'Craqueleur Légendaire',
  'Gardienne des Égouts (Entrailles de Brâkmar, Canaux méphitiques)',
  'Gelée Royale Fraise',
  'Maître Corbac',
  'Blop Multicolore Royal',
  'Corailleur Magistral',
  'Gourlo le Terrible',
  'Meulou',
  'Wa Wabbit',
  'Moon',
  'Koulosse',
  'Skeunk',
  'Abraknyde ancestral',
  'Hanshi',
  'Tynril Ahuri',
  'Tynril Consterné',
  'Tynril Déconcerté',
  'Tynril Perfide',
  'Gelée Royale Citron',
  'Founamboul',
  'Bworker',
  'Sphincter Cell',
  'Minotot',
  'Silf le Rasboul Majeur',
  'Crocabulia',
  'Haute Truche',
  'Chêne mou',
  'Ougah',
  'Kimbo',
]
