export const monsters = [
  'Souris Grise (Cryptes du cimetière)',
  'Moskito (Campagne d\'Amakna, Bord de la forêt maléfique)',
  'Arakne (Campagne d\'Amakna)',
  'Boufton Blanc (Coin des Bouftous, Tainéla)',
  'Boufton Noir (Coin des Bouftous, Tainéla)',
  'Tofu Maléfique (Cimetières, Cryptes)',
  'Arakne Malade (Souterrains d\'Astrub)',
  'Piou Bleu (Astrub, Bonta, Brâkmar, Village d\'Amakna, Sufokia)',
  'Piou Jaune (Astrub, Bonta, Brâkmar, Village d\'Amakna, Sufokia)',
  'Piou Rouge  (Astrub, Bonta, Brâkmar, Village d\'Amakna, Sufokia)',
  'Piou Vert (Astrub, Bonta, Brâkmar, Village d\'Amakna, Sufokia)',
  'Piou Violet(Astrub, Bonta, Brâkmar, Village d\'Amakna, Sufokia)',
  'Piou Rose (Astrub, Bonta, Brâkmar, Village d\'Amakna, Sufokia)',
  'Flammèche Air (Plaine des Scarafeuilles)',
  'Flammèche Eau (Plaine des Scarafeuilles)',
  'Flammèche Feu (Plaine des Scarafeuilles)',
  'Flammèche Terre (Plaine des Scarafeuilles)',
  'Larve Bleue (Bord de la Forêt Maléfique, Côte d\'Asse, Port de Madrestam, Rivière Kawaii, Prairies d\'Astrub)',
  'Crabe (Rivages de Sufokia)',
  'Tofu (Champs des Ingalsse)',
  'Tofu Malade (Souterrains d\'astrub)',
  'Champ Champ (Campagne d\'Amakna, Coin des Bouftous)',
  'Pissenlit Diabolique (Rives Iridescentes, Champs d\'Astrub)',
  'Arakne des Égouts (Égouts d\'Astrub)',
  'Bandit Manchot (Passage vers Brâkmar)',
  'Rose Démoniaque (Rives Iridescentes, Coin des Bouftous)',
  'Gelée Bleue (Péninsule des Gelées, Gelaxième dimension)',
  'Gelée Menthe (Péninsule des Gelées, Gelaxième dimension)',
  'Kwoan (Cimetière d\'Amakna)',
  'Larve Verte (Prairies d\'Astrub, Bord de la Forêt Maléfique, Côte d\'Asse, Port de Madrestam, Rivière Kawaii)',
  'Bouftou (Coin des Bouftous, Tainéla)',
  'Kolérat (Désolation de Sidimote)',
  'Larve Orange (Bord de la Forêt Maléfique, Côte d\'Asse, Port de Madrestam, Prairies d\'Astrub, Rivière Kawaii)',
  'Boulanger Sombre (Passage vers Brâkmar, Territoire des Bandits)',
  'Black Tiwabbit (Île de la Cawotte)',
  'Tiwabbit (Île de la Cawotte)',
  'Tiwabbit (Île de la Cawotte)',
  'Tournesol Sauvage (Champs d\'Astrub, Rives Iridescentes)',
  'Bandit du clan des Roublards (Territoire des Bandits)',
  'Gobet (Campement des Bworks, Campement des Gobelins, Montagne basse des Craqueleurs)',
  'NodKoko (Plage de la Tortue)',
  'Trukikol (Jungle Interdite)',
  'Tikokoko (Plage de la Tortue)',
  'Sanglier (Bord de la forêt maléfique, Forêt d\'Amakna, Forêt d\'Astrub, Milifutaie)',
  'Champa Vert (Clairière de Brouce Boulgoure)',
  'Crowneille (Désolation de Sidimote)',
  'Vampire (Cryptes)',
  'Biblop Coco (Lac de Cania)',
  'Biblop Griotte (Lac de Cania)',
  'Biblop Indigo (Lac de Cania)',
  'Biblop Reinette (Lac de Cania)',
  'Gob-trotteur (Campement des Bworks, Campement des Gobelins, Montagne basse des Craqueleurs)',
  'Milirat Strubien (Égouts d\'Astrub)',
  'Boo (Coin des Boos, Marécages)',
  'Prespic (Bord de la Forêt Maléfique, Forêt d\'Amakna, Forêt d\'Astrub, Milifutaie)',
  'Cochon de Lait (Plaine des Porkass)',
  'Tortue Jaune (Plage de la Tortue)',
  'Wabbit (Île de la Cawotte, Îlot de la Couronne)',
  'Chef de Guerre Bouftou (Coin des Bouftous, Tainéla)',
  'Berger Porkass (Plaine des Porkass',
  'Croc Gland (Désolation de Sidimote)',
  'Floristile (Plantala)',
  'Tortue Bleue (Plage de la Tortue)',
  'Tortue Rouge (Plage de la Tortue)',
  'Tortue Verte (Plage de la Tortue)',
  'Corbac (Pénates des Corbac)',
  'Etoile de la Mer d\'Asse (Calanques d\'Astrub)',
  'Pichon Blanc (Calanques d\'Astrub)',
  'Pichon Bleu (Calanques d\'Astrub)',
  'Pichon Orange (Calanques d\'Astrub)',
  'Pichon Vert (Calanques d\'Astrub)',
  'Bambouto (Plantala)',
  'Maître Vampire (Cryptes)',
  'Minoskito (Île du Minotoror)',
  'Noeul (Cryptes)',
  'Milimulou (Forêt d\'Amakna, Forêt d\'Astrub, Milifutaie)',
  'Fourbasse (Jungle Interdite)',
  'Bulbiflore (Bambusaie de Damadrya)',
  'Bwork Mage (Campement des Bworks, Montagne basse des Craqueleurs)',
  'Croc Gland Enragé (Bordure de Brâk',
  'Rose Obscure (Rives Iridescentes)',
  'Black Wabbit (Île de la Cawotte, Îlot de la Couronne)',
  'Mineur Sombre (Passage vers Brakmâr, Territoire des Bandits)',
  'Bwork Archer (Campement des Bworks, Montagne basse des Craqueleurs)',
  'Champa Bleu (Clairière de Brouce Boulgoure)',
  'Champa Marron (Clairière de Brouce Boulgoure)',
  'Champa Rouge (Clairière de Brouce Boulgoure)',
  'Craqueboule (Montagne des Craqueleurs, Montagne basse des Craqueleurs)',
  'Mandrine (Île du Minotoror)',
  'Ishigro Pake (Terrdala)',
  'Gargrouille (Cimetière d\'Astrub)',
  'Dragodinde Amande Sauvage (Territoire des Dragodindes Sauvages)',
  'Gelée Fraise (Péninsule des Gelées)',
  'Wabbit Squelette (Îlot des Tombeaux)',
  'Chafer Invisible (Cimetière, Bois de Litneg)',
  'Craqueleur (Montagne des Craqueleurs, Montagne basse des Craqueleurs)',
  'Bwork (Campement des Bworks, Montagne basse des Craqueleurs)',
  'Abraknyde (Orée de la Forêt des Abraknydes)',
  'Kraméléhon (Île du Minotoror)',
  'Scarafeuille Blanc (Plaine des scarafeuilles)',
  'Scarafeuille Bleu (Plaine des scarafeuilles)',
  'Scarafeuille Rouge (Plaine des scarafeuilles)',
  'Scarafeuille Vert (Plaine des scarafeuilles)',
  'Rib (Cimetière d\'Amakna, Bois de Litneg)',
  'Blop Coco (Lac de Cania)',
  'Blop Griotte (Lac de Cania)',
  'Blop Indigo (Lac de Cania)',
  'Blop Reinette (Lac de Cania)',
  'Cochon de Farle (Labyrinthe du Dragon Cochon, Territoire des Porcos)',
  'Scaratos (Labyrinthe du Minotoror)',
  'Boomba (Chemin du Crâne)',
  'Tronknyde (Orée de la Forêt des Abraknydes)',
  'Chafer Fantassin (Cimetière d\'Amakna, Bois de Litneg)',
  'Pichon Kloune (Donjon Ensablé)',
  'Abrakne (Orée de la Forêt des Abraknydes)',
  'Chafer (Cimetières, Bois de Litneg)',
  'Crocodaille (Marécages)',
  'Scélérat Strubien (Égouts d\'Astrub)',
  'Scorbute (Désolation de Sidimote)',
  'Dragodinde Rousse Sauvage (Territoire des Dragodindes Sauvages)',
  'Forgeron Sombre (Passage vers Brâkmar, Territoire des Bandits)',
  'Crustorail Kouraçao (Plage de Corail)',
  'Crustorail Malibout (Plage de Corail)',
  'Crustorail Morito (Plage de Corail)',
  'Crustorail Passaoh (Plage de Corail)',
  'Bulbuisson (Plantala)',
  'Arakne Majeure (Orée de la Forêt des Abraknydes)',
  'Akakwa (Akwadala)',
  'Grand Pa Wabbit - Wo Wabbit (Îlot de la Couronne, Îlot de Waldo)',
  'Cavalier Porkass (Plaine des Porkass)',
  'Amlub (Baie de Cania, Village des Dopeuls)',
  'Codem (Baie de Cania, Village des Dopeuls)',
  'Kirevam (Baie de Cania, Village des Dopeuls)',
  'Let Emoliug (Baie de Cania, Village des Dopeuls)',
  'Aboub (Mine des Dopeuls, Village des Dopeuls)',
  'Gink (Mine des Dopeuls, Village des Dopeuls)',
  'Negbib (Mine des Dopeuls, Village des Dopeuls)',
  'Nipul (Mine des Dopeuls, Village des Dopeuls)',
  'Osurc (Mine des Dopeuls, Village des Dopeuls)',
  'Susej (Baie de Cania, Village des Dopeuls)',
  'Kokoko (Plage de la Tortue)',
  'Chafer Archer (Cimetière des Héros, Cimetière des Torturés, Bois de Litneg)',
  'Chafer Lancier (Cimetière des Héros, Cimetière des Torturés, Bois de Litneg)',
  'DoK Alako (Canyon Sauvage, Lacs Enchantés, Forêt de Kaliptus)',
  'Koalak Immature (Forêt de Kaliptus, Lacs enchantés)',
  'Gamino (Labyrinthe du Minotoror)',
  'Ramane d\'Egoutant (Égoûts de Bonta et de Brâkmar, Souterrains du Château d\'Amakna)',
  'Le Ouassingue Entourbé (Tourbière d\'Otomai)',
  'Le Ouassingue (Cimétière d\'Astrub)',
  'La Ouassingue (Cimétière d\'Astrub)',
  'Palmifleur Malibout (Plage de Corail)',
  'Palmifleur Morito (Plage de Corail)',
  'Palmifleur Passaoh (Plage de Corail)',
  'Sanglier Des Plaines (Plaine des Porkass)',
  'Abraknyde Vénérable (Forêt Sombre)',
  'Craqueleur des plaines (Plaines Rocheuses)',
  'Fangshu (Aerdala)',
  'Chafer d\'élite (Cimetières des Héros, Cimetière des Torturés)',
  'Maître Bolet (Routes Rocailleuses)',
  'Craqueboule Poli (Plaines Herbeuses)',
  'Ino-Naru (Aerdala)',
  'Kanniboul Archer (Forêt des Masques)',
  'Kanniboul Jav (Forêt des Masques)',
  'Kanniboul Sarbak (Forêt des Masques)',
  'Kanniboul Thierry (Forêt des Masques)',
  'Sarkapwane (Akwadala)',
  'Rat d\'Egoutant (Egoûts de Bonta et de Brâkmar, Souterrains du Château d\'Amakna)',
  'Palmifleur Kouraçao (Plage de Corail)',
  'Macien (Laboratoire de Brumen Tinctorias)',
  'Kwak de Vent (Montagne des Craqueleurs)',
  'Kwak de Flamme (Montagne des Craqueleurs)',
  'Kwak de Glace (Montagne des Craqueleurs)',
  'Kwak de Terre (Montagne des Craqueleurs)',
  'Porsalu (Territoire des Porcos)',
  'Dragacé (Sanctuaire des Dragoeufs)',
  'Chafer Draugr (Cimetière des Héros, Cimetière des Torturés, Cimetière d\'Amakna)',
  'Vétauran (Routes Rocailleuses)',
  'Crachefoux (Feudala)',
  'Serpiplume (Labyrinthe du Minotoror)',
  'Corailleur (Plage de Corail)',
  'Lolojiki (Terrdala)',
  'Raul Mops (Rivages Sufokien)',
  'Shinibaru (Atelier du Tanukouï San)',
  'Betto (Akwadala)',
  'Moumoule (Rivages Sufokien',
  'Canondorf (Chemin du Crâne)',
  'Nakunbra (Chemin du Crâne)',
  'Don Duss Ang (Labyrinthe du Dragon Cochon)',
  'DragOeuf Calcaire (Presqu\'île des Dragoeufs)',
  'DragOeuf Argile (Presqu\'île des Dragoeufs)',
  'DragOeuf Charbon (Presqu\'île des Dragoeufs)',
  'DragOeuf Ardoise (Presqu\'île des Dragoeufs)',
  'Koalak Coco (Canyon Sauvage)',
  'Koalak Griotte (Canyon Sauvage)',
  'Koalak Indigo (Canyon Sauvage)',
  'Koalak Reinette (Canyon Sauvage)',
  'Rat d\'Hyoactif (Egoûts de Bonta et de Brâkmar)',
  'Sparo (Arche d\'Otomai)',
  'Chiendent (Jungle Obcure)',
  'Fantôme Apero (Bordure de Brâkmar)',
  'Fantôme aux Plates (Bordure de Brâkmar)',
  'Fantôme Hicide (Bordure de Brâkmar)',
  'Fantôme Égérie (Bordure de Brâkmar)',
  'Don Dorgan (Labyrinthe du Dragon Cochon)',
  'Barbroussa (Arche d\'Otomai)',
  'Le Flib (Arche d\'Otomai)',
  'Nerbe (Jungle Obscure)',
  'Chef Crocodaile (Marécages)',
  'Serpentin (Champs de Cania)',
  'Kanigrou (Routes Rocailleuses)',
  'Bitouf des plaines (Plaines herbeuses)',
  'Craqueleur poli (Plaines herbeuses)',
  'Mufafah (Plaines herbeuses)',
  'Mulou (Hauts des Hurlements)',
  'Kurookin (Aerdala)',
  'Kido (Plaines herbeuses)',
  'Kilibriss (Plaines herbeuses)',
  'Larve Champêtre (Champs de Cania)',
  'Bourdard (Champs de Cania)',
  'Foufayteur (Routes Rocailleuses)',
  'Panthégros (Dents de Pierre)',
  'Dragueuse (Sanctuaire des Dragoeufs)',
  'Guerrier koalak (Vallée de la Morh\'Kitu)',
  'Kokom (Akwadala)',
  'Orfélin(Dents de Pierre)',
  'Warko marron (Forêt de Kaliptus, Canyon Sauvage)',
  'Parashukouï (Terrdala)',
  'Abraknyde sombre (Forêt Sombre)',
  'Alhyène (Dents de Pierre)',
  'Fossoyeur koalak (Cimetière primitif)',
  'Koalak forestier (Forêt de Kaliptus)',
  'Piralak (Lacs enchantés)',
  'Pékeualak (Lacs enchantés)',
  'Gloutovore (Jungle Interdite)',
  'Abrakne sombre (Forêt Sombre)',
  'Dragodinde dorée sauvage (Territoire des Dragodindes Sauvages)',
  'Chevaucheur koalak (Cimetière primitif)',
  'Meupette (Tronc de l\'Arbre Hakam)',
  'Grenufar (Plantala)',
  'Dragnarok (Sanctuaire des Dragoeufs)',
  'Draguaindrop(Sanctuaire des Dragoeufs)',
  'Bizarbwork (Pics de Cania)',
  'Médibwork (Pics de Cania)',
  'Krambwork (Pics de Cania)',
  'Mégabwork (Pics de Cania)',
  'Disciple Zoth (Village des Zoths)',
  'Brouture (Jungle Obscure)',
  'Koalak sanguin (Vallée de la Morh\'Kitu)',
  'Bitouf sombre (Jungle Obscure)',
  'Floribonde (Jungle Obscure)',
  'Fécorce (Jungle Obscure)',
  'Koalak Farouche (Vallée de la Morh\'Kitu)',
  'Mama Koalak (Canyon Sauvage)',
  'Momie Koalak (Cimetière primitif)',
  'Bourbassingue (Tourbière d\'Otomai)',
  'Warko Violet (Vallée de la Morh\'Kitu)',
  'Gamine Zoth (Village des Zoths)',
  'Guerrier Zoth(Village des Zoths)',
  'Tourbassingue (Tourbière d\'Otomai)',
  'Abrakleur sombre (Jungle Obscure)',
  'Dragoss Calcaire (Souterrains des Dragoeufs, Village des Dragoeufs)',
  'Dragoss Argile (Souterrains des Dragoeufs, Village des Dragoeufs)',
  'Dragoss Charbon (Souterrains des Dragoeufs, Village des Dragoeufs)',
  'Dragoss Ardoise (Souterrains des Dragoeufs, Village des Dragoeufs)',
  'Rouquette (Feudala)',
  'Tétonuki (Terrdala)',
  'Boumbardier (Feudala)',
  'Drakoalak (Canyon Sauvage)',
  'Fauchalak (Vallée de la Morh\'Kitu)',
  'Maître koalak (Cimetière Primitif)',
  'Poolay (Tronc de l\'Arbre Hakam, Feuillage de l\'Arbre Hakam)',
  'Malle Outillée (Massif de Cania)',
  'Robot Fléau (Massif de Cania)',
  'Robionicle (Massif de Cania)',
  'Kaniblou (Dents de Pierre)',
  'Troollaraj (Bois de Litneg)',
  'Sergent Zoth (Village des Zoths)',
  'Maître Zoth (Village des Zoths)',
  'Kaskargo (Feuillage et Tronc de l\'Arbre Hakam)',
  'Bitouf Aérien (Feuillage et Tronc de l\'Arbre Hakam)',
  'Abrakleur Clair (Tronc de l\'Arbre Hakam)',
  'Pétartifoux (Feudala)',
  'Champaknyde (Domaine des Fungus)',
  'Tromperelle (Domaine des Fungus)',
  'Champodonte (Caverne des Fungus)',
  'Champbis (Caverne des Fungus)',
  'Champ à Gnons (Domaine et Caverne des Fungus)',
  'Champmane (Domaine et Caverne des Fungus)',
  'Tsukinochi (Cimetière de Grobe)',
  'Tambouraï (Cimetière de Grobe)',
  'Onabu-Geisha (Cimetière de Grobe)',
  'Jianshi-Nobi (Cimetière de Grobe)',
  'Lichangoro (Aerdala)',
  'Roissingue (Tourbière d\'Otomaï)',
  'Madura (Monts des Tombeaux)',
  'Bakazako (Monts des Tombeaux)',
  'Kaonashi (Monts des Tombeaux)',
  'Tsume-Bozu (Monts des Tombeaux)',
];
